### ISSUE TITLE
Configurable namespace and ConfigMap

### ISSUE THREAD

**Issue by simonfuhrer** [google/metallb#132]
**Is this a bug report or a feature request?**:
feature request

**What happened**:
The namespace and the required ConfigMap Name are currently hard-coded. This should be controlled by environment variables which are read out when starting the pods (controller and speaker).  This would allow us to set up different BGP peers per Failure Domains. 

I could try to implement this. It looks like this is no big deal.
Later it should be possible to use Node Labels for this purpose #52.  

What do you think of that?

**Comment by danderson** [comment]
I'm not sure I understand the use case for this. Can you describe the problem you're trying to solve?

Running multiple copies of MetalLB in a cluster is definitely not going to work right, because the controllers will fight each other for control of the Service objects. Supporting multiple cooperating controllers is a significant amount of work/complexity, so I want to understand the use case before we go down that road.

Multiple distinct speakers is possible, but once #52 is implemented it should be unnecessary... So I think I'm missing something about your setup and goal.

**Comment by simonfuhrer** [comment]
Hi, Dave. 

I would like to establish BGP peers in different Failure Domains. This is currently not possible. If the configMap could be configured, two different DaemonSets per Failure Domain could be created. (with different BGP peers) 

The controllers deployment remains the same with one replica. 

Would that work?

**Comment by danderson** [comment]
Turns out, I implemented this in 0.4.3, because it's required to make Helm charts work :). `--config-ns` and `--config` do the thing now. Although, I still don't recommend running multiple MetalLB deployments, 0.4 also has node selectors for BGP sessions, which I think is better for what you're trying to do.
