### ISSUE TITLE
ARP speaker: metrics for ARP responses sent

### ISSUE THREAD

**Issue by jpds** [google/metallb#133]
**Is this a bug report or a feature request?**: Feature request

**What happened**: I noticed that there was a metric for `metallb_speaker_announced` which seems to be `1` across all my services. It'd be useful to also have a metric for actual ARP(/other) responses the speaker sends out so that traffic across the nodes can be correlated.

**Comment by mdlayher** [comment]
Seems reasonable to me, and I assume the future NDP speaker would have comparable metrics as well. Not sure yet if it makes sense to put them both behind the same interface though.

**Comment by miekg** [comment]
Note that `metallb_speaker_announced` is used both by bgp and arp and it's set to one because you want to have the labels it exports, e.g.:
~~~
metallb_speaker_announced{instance="192.168.1.109:7472",ip="192.168.1.252",job="metallb-speaker",node="node1",protocol="arp",service="default/coredns"}
~~~
tells you everything about this VIP. I use it in Grafana like:
~~~
sum(metallb_speaker_announced) by (protocol,service, ip)
/
count(metallb_speaker_announced) by (protocol,service, ip)
~~~
Note that this should include the master election is well, i..e all speakers are announcing, but in the case of arp only 1 should actually reply to arp requests.

Traffic sent would be useful yes; but the metric should also be useful for bgp and ndp (as @mdlayher mentioned)

**Comment by danderson** [comment]
We could go 2 ways here. One set of metrics (packets_received/packets_sent) for all protocols, or separate metrics for ARP+NDP and BGP.

The question is: what does packets_received/sent mean for BGP? It's not a packet-oriented protocol. Logically, the metric I want is number of updates sent/received, which technically might count as a "packet"... But the metric name is a bit misleading.

I think in practice it would be fine to just have separate metrics for each protocol, or at least separate BGP from ARP/NDP because they have fundamentally different behaviors. WDYT?

**Comment by miekg** [comment]
but how will separate metrics looks like?

* arp_packets_received
* ndp_packets_received
* bgp_updates_received

? And then more for each protocol? That can work; there is some beauty into having the protocol be a label, but using it in the metric name works as well.

Basically what I'm saying here: consistency would be good; either always as a label or always in the name, but no miss and match.

**Comment by danderson** [comment]
I was thinking either what you said, or:

packets_received{proto=arp}
packets_received{proto=ndp}
updates_received{proto=bgp4}
updates_received{proto=bgp6}

Each metric is only defined for the protocols where it makes sense: BGP has no packets, so it doesn't set packets_received{proto=bgp4}. ARP and NDP don't have updates, so they don't set updates_send{proto=arp}.

It's still a bit ugly because we have metrics that apply to non-overlapping sets of protocols. But maybe someday we could support a protocol where both metrics make sense (e.g. OSPF is both update-oriented and packet-oriented).

But I would also be okay with per-protocol metrics, I guess. That makes it very clear that each protocol has its own metrics...

**Comment by miekg** [comment]
It's a bit bikeshedding at this point. Let me just add how I do this I
coredns where each plugin exports its own named set of metrics.
