### ISSUE TITLE
Can not make MetalLB work with kube-router

### ISSUE THREAD

**Issue by tiukhtinvladimir** [google/metallb#164]
**Is this a bug report or a feature request?**:

More likely a feature

**What happened**:

MetalLb works perfect with kube-proxy but not with kube-router

**What you expected to happen**:

It is possibly a kube-router issue, but I expected load balancer just work

**How to reproduce it (as minimally and precisely as possible)**:

Flush your iptables rules, stop kube-proxy, substitute it with kube-router

**Comment by danderson** [comment]
Yup, see #160. kube-router and metallb are known to be incompatible, because of https://github.com/cloudnativelabs/kube-router/issues/242 . MetalLB relies on kube-proxy (or its equivalent) to program the dataplane on every node, and kube-router currently does not. There's nothing I can really do about this, other than wait for kube-router to support loadBalancer endpoints.

**Comment by tiukhtinvladimir** [comment]
@danderson thanks for your prompt response. I noticed as well, that kube-proxy can not work with metallb in ipvs mode. I tried ARP mode and kube-proxy in iptables mode and it works. Switching to ipvs breaks connectivity. Possibly because iptables does DNAT on prerouting stage when ipvs requires packet to be accepted by kernel

**Comment by danderson** [comment]
Yup, that's #153. I haven't had time to diagnose it yet, but I suspect IPVS mode in kube-proxy might also be ignoring LoadBalancer IPs.
