### ISSUE TITLE
Minikube does not use stable IP ranges across OSes/versions, which breaks the tutorial

### ISSUE THREAD

**Issue by xnaveira** [google/metallb#19]
Maybe it's just me but my minikube default config is to use 10.96.0.0/12 as a service cidr so the 10.0.0.x addresses in the tutorial manifests don't work out of the box.

**Comment by xnaveira** [comment]
Also, the tutorial wasn't working for me anymore. I saw that the test-bgp pod was only running bird, nor quagga or gobgp. Then I removed the quagga/gobgp peer config from the configmap and it began working. I think it would be a good thing that bgp-speaker starts with the peers that work instead for waiting for all of them to come up.

**Comment by danderson** [comment]
Thank you for the bug report! It sounds like I broke the tutorial with some recent changes. Sorry about that!

I'm looking at it now. Could you give me a bit more info:
- OS you're running minikube on
- Ouput of `minikube version`
- Output of `kubectl version` when it's configured to talk to minikube

The issue you had with the configmap is weird, MetalLB always tries to connect to all peers independently of each other, so even if Quagga and GoBGP were down, the config with 3 peers should still work and connect to Bird.

I suspect the issue is my crappy attempt to lock the documentation to the v0.1.0 release, investigating...

**Comment by danderson** [comment]
Okay, I've found the root cause. For some reason, quay.io is no longer updating the "latest" tag when it builds new container images, so the manifests boot a MetalLB that is 7 days old, and a test-bgp-router that is 4 days old.

Notably, the 7 day old MetalLB is missing a bugfix for handling multiple BGP peers, which is probably why your BGP speaker was not connecting correctly.

I can fix this easily by tweaking the manifest to pull the master image for now, while I figure out how to explain to quay the concept of "latest". Working on it...

**Comment by xnaveira** [comment]
Hey, I see that you have figured most of it but for what is worth:
 - OS: MacOS High Sierra 10.13.1
 - minikube: v0.24.1
 - kubectl: 1.8.0

Thanks for looking at it.

**Comment by danderson** [comment]
So, the patch I just pushed should make the tutorial mostly work, specifically:
- test-bgp-router should now have the 3 routers (bird, quagga, gobgp)
- MetalLB's bgp-speaker should correctly connect to all peers

Remaining issue is that your minikube is setting up the cluster differently from mine, so the tutorial manifests are not correct. I use minikube on linux, so I'm wondering if it's a mac-specific difference in minikube's configs...

I will continue looking into that tonight, and see if maybe there's a way to make the manifests generic, or to pass minikube some settings to configure things uniformly.

Thanks again for the bug reports! Sorry you had a bumpy experience. Hopefully now you can experiment a bit, even though you will still need to edit the service IPs and MetalLB peering config for now.

**Comment by xnaveira** [comment]
I could work with it without problems once i figured out that the speaker wouldn't work until i removed the non existing peers, no problem. I'm testing on a bare-metal coreos cluster as well, i opened another issue regarding that: https://github.com/google/metallb/issues/21

Again, thanks for looking at it, I will continue to experiment and see if this can be used on our setup. We already have bgp running for the physical hosts and the pods so this looks very promising!

**Comment by danderson** [comment]
The non-existing peers problem was actually 5df1b39f4df8839366f20b7b4e9b7837f5441a0a , I screwed up the config parsing in bgp-speaker, so whenever there was >1 peer in the config, bgp-speaker made all the BGP sessions try to connect to the _last_ peer in the config.

Now that I've updated the manifests to use a recent build of MetalLB, multiple peers should work fine, even if some peers are down.

**Comment by xnaveira** [comment]
I haven't found out yet why is minikube assigning another network in mac but running minikube like this ```minikube start --extra-config=apiserver.ServiceClusterIPRange="10.0.0.0/12"``` sets up the network for the services as test-bgp wants it.

**Comment by danderson** [comment]
Thanks for the workaround! I still want to do some research and figure out if minikube offers any guarantees on IP address stability, but this is very useful. If minikube doesn't offer any guarantees, I can just add a note/warning to the tutorial that explains extra steps.

**Comment by danderson** [comment]
For the IP address issues: it looks like Minikube 0.24 might have renumbered the virtual networks it uses. I did my development and testing on Minikube 0.23, so that might be the problem. I'm upgrading to Minikube 0.24 to test more.

**Comment by danderson** [comment]
Bingo, that's the problem. With 0.24.1, the tutorial is broken for me as well. The service IP range switched to 10.96.0.0/24.

Fixing the manifest and tutorials...

**Comment by xnaveira** [comment]
Confirmed that ```fab start``` worked out of the box for me now.
