### ISSUE TITLE
Check in vendor/ or not?

### ISSUE THREAD

**Issue by miekg** [google/metallb#20]
How do you compile?

```
% ls                                                                                                                ~/g/src/github.com/miekg/metallb master + deb
AUTHORS       CONTRIBUTING.md  dockerfiles/  fabfile.py  glide.yaml  LICENSE     README.md
bgp-speaker/  controller/      docs/         glide.lock  internal/   manifests/  test-bgp-router/
% cd controller                                                                                                     ~/g/src/github.com/miekg/metallb master + deb
% ls                                                                                                     ~/g/src/github.com/miekg/metallb/controller master + deb
main.go  service.go
% go b                                                                                                   ~/g/src/github.com/miekg/metallb/controller master + deb
main.go:23:2: use of internal package not allowed
main.go:24:2: use of internal package not allowed
main.go:25:2: use of internal package not allowed
%                                                                                                        ~/g/src/github.com/miekg/metallb/controller master + deb
```
Also to use `go.universe.tf` don't you need to add a canonical import path?
`package pdf // import "rsc.io/pdf"`

**Comment by miekg** [comment]
of course; some imports fail because it's in my local repo, which should be fixed with creating a symlink of go.universe.tf. Let me try that actually.

**Comment by danderson** [comment]
In general, when hacking on forks, the best approach is to `go get go.universe.tf/metallb`, then `git remote add miekg <URL to your fork>` in that repo. That way you can pull from upstream, push to your fork, rebase, etc. and the code still compiles correctly because all the import paths make sense. You just switch between the upstream implementation and your customizations.

**Comment by miekg** [comment]
Ok.. thanks. But if you want that you should probably use canonical import
paths.

**Comment by danderson** [comment]
Hmm, you're right. I didn't set canonical import paths because I thought it was useless (only binaries and internal packages), but I guess it helps to avoid this issue.

**Comment by xnaveira** [comment]
This is giving me problems too, unable to compile.

**Comment by halfa** [comment]
>  Why not vendor/ in .gitignore?

Maybe because he use it in a global `.gitignore` (like I do).

**Comment by miekg** [comment]
fyi: vendor should be checked in.

**Comment by danderson** [comment]
See https://github.com/google/metallb/blob/master/docs/hacking.md#building-the-code - After cloning the repository, run `glide install` to fetch the correct versions of dependencies and recreate the vendor directory.

I guess I could check in the `vendor/` directory, the reason I didn't is that it's a ton of bytes, and `glide install` can reconstruct the exact correct state... But you have to run it. Adding the vendor directory creates some complexity vs. Google's policies, because Google says that any external code that I check in must be under `third_party/`, which is incompatible with Go vendoring. Symlink hacks should work, at the cost of more ugliness...

WDYT? Still worth it to check in the vendored dependencies?

As for adding to .gitignore... I just forgot. I've pushed a change to do that.

**Comment by miekg** [comment]
Had the same reservations with coredns, in the end we a) vendored and b) checked the whole thing in: 34M	vendor

If you just add a `vendor` dir and then a plain `third_party -> vendor` symlink, does that count?

**Comment by danderson** [comment]
Okay, well, CoreDNS's real world experience outweighs my opinions :). Preparing a CL now to check in the vendor files, and a second one to add canonical import paths everywhere.

**Comment by xnaveira** [comment]
IMHO not checking in vendor is the right thing to do, that's what glide is
for and that's why I thought it was a good idea to have it in gitignore.

**Comment by danderson** [comment]
Okay, so MetalLB's vendor directory is 104MB (lol k8s client library).

Advantage of checking in:
- No extra steps required to compile. Currently you _must_ run `glide install`, otherwise MetalLB will not compile, because the k8s client library doesn't build if you don't use the vendored versions.
- MetalLB is resistant to dependencies disappearing (e.g. someone deleting their repo)

Advantage of keeping as-is:
- MetalLB's repository is smaller, faster to clone (but you still have to download the 104MB afterwards, because `glide install` is not optional).

So, given that `glide install` is not optional when using the k8s client library... The question is pretty much "download dependencies now, or immediately afterwards?" Given that, I think the argument that it's easier to just bundle the deps is good?

**Comment by miekg** [comment]
We also have k8s client in coredns and that is lighter. Maybe you'll need
more functionality and hence more of k8s?

**Comment by danderson** [comment]
I pruned everything except the k8s client library, and it's pretty much the same size. Looks like v5.x of the k8s library is just way larger than v4.x (the one coredns uses).

I think one reason is that v5 is starting a large refactor that implies having duplicate copies of some packages. So, it might get better in v6?...

**Comment by halfa** [comment]
While the debate is open, you might consider that the vendors might evolve over time, adding to the weight of the overall repository. And a glide install is pretty much a painless one-liner once you've got your go setup right, and glide cache can be reused across projects. On top of that, if you (really) fear about your dependencies, then I would be better in my opinion to keep a separate mirror of their repos instead of relying on a single-revision, commited code inside the projet tree.

**Comment by danderson** [comment]
I'm not really worried about the "dependency goes away" problem. It could happen, but it's relatively easy to fix, and unlike node/npm, breaking the dependency tree doesn't break existing releases.

Good point about the glide cache, it means there's a good chance you don't need to redownload all 104MB on each checkout. And as you say, checking into git means the repository will be huge for ever.

How about we stick to `glide install` for now, and see how we do? I've added canonical import paths and .gitignore, and there's documentation in the hacking guide for how you should set up the client to build the code.

**Comment by miekg** [comment]
Note that the Go community is moving to `dep` (using this for coredns and miekg/dns).

Not sure if this is written down, but IIRC the contract for a Go repo is: I go get it, and go build, builds it; no extra steps required.

Site note: I hate vendoring

**Comment by danderson** [comment]
`dep` doesn't work with the v5 of the k8s client, because `dep` doesn't correctly implement some kind of bizarre transitive dependency locking insanity that the k8s client relies on. I lost a couple of days trying to make `dep` work before a k8s dev told me "oh yeah, that never worked, we should remove it from our documentation."

The contract you mention is nice, but I don't think that's actually official at all. There are tons of repositories out there that require an additional setup step before compiling, including k8s itself.

I'm really torn: I like "just get and build" as a model, but empirically that's already not working any more. And the cost of making that model work is that MetalLB's repository becomes literally 100x larger and slower to clone. Intuitively that feels like a painful tradeoff :(

**Comment by miekg** [comment]
WTF! So coredns can't upgrade to v5 because of dep... *sigh*

Anyway; as long as I can download this repo and perform `make` and it builds it's fine, I guess and after that a go build should work.

**Comment by danderson** [comment]
I'm still undecided, so I asked twitter: https://twitter.com/dave_universetf/status/938910522711228416 . I'm really curious what the rest of the Go community does, I only know about my tiny slice of the universe, and we don't check in vendor/. But Miek's slice of the universe disagrees.

So, I'm just going leave the poll running for 24h, and then do whatever the internet tells me to do. And then I can go back to writing code and fixing bugs :)

**Comment by xnaveira** [comment]
While you are at it, adding *.pyc to the gitignore file wouldn't hurt :P

**Comment by xnaveira** [comment]
At some point the go.universe.tf paths were reintroduced breaking the build process again.

**Comment by miekg** [comment]
(my GOPATH is `~/g`), I've checked it out in, `~/g/src/go.universe.tf/metallb` and then have a symlink from
`/home/miek/g/src/github.com/miekg/metallb` -> `~/g/src/go.universe.tf/metallb`, so my CDPATH setup works.
Now I can:
% cd metallb
% cd $(pwd -P)
and then things compile - not optimal, but works for me.

**Comment by xnaveira** [comment]
Ok, that's probably because you checkout go.universe.tf repo and then you simlink github's, I did the other way around. My understanding is that at some point all the ```go.universe.tf/metallb``` where replaced by ```github.com/google/metallb``` and now when i pulled the latest version i got them back. I did the replace on my side and i can build normally now. Just giving you the pov of an outsider that uses github as primary source.
