### ISSUE TITLE
Align helm chart and manifest

### ISSUE THREAD

**Issue by chrisplo** [google/metallb#268]
This is a feature request to have the manifest generated by the helm chart to keep them aligned.

The chart defaults could create a manifest that is effectively the same as the current manifest

Then going foward, changes would go to the chart and then templating the chart would reflect the changes in the manifest, instead of the chart needing to play catchup.

**Comment by chrisplo** [comment]
i found the Makefile target, got thrown off by "Currently, the Helm chart is not up to date with the latest release of MetalLB." in the docs.

**Comment by danderson** [comment]
Yeah, sorry about that. The issue is that I don't have commit rights on the helm charts repo, so whenever I make a new release it takes a code review cycle to actually update helm. Depending on how busy the repo owners are, it can take a few hours, or up to a week. That's why I have the disclaimer in there.
