### ISSUE TITLE
default route

### ISSUE THREAD

**Issue by kfox1111** [google/metallb#319]
Is metallb expected to work with l2 mode where the pool of addresses its handing out are not associated with the default route?

I've got 2 sets of addresses, 1 smaller set that is the default network. its routable ip space, so I don't want to waste them. I have a second, private ip space routable in the org that is being handed out by metallb. its arping for them, and everything works fine internally but externally its not working.

**Comment by danderson** [comment]
"It depends". What you're describing is asymetric routing. Some networks allow this, others do not. So, it depends on your specific cluster and network topology. Unfortunately I can't help with either of those due to lack of time. But if your environment supports asymetric routing, then metallb will work fine within that environment.

**Comment by kfox1111** [comment]
Hmm... I guess I was thinking, that if the svc ip address was assigned to the machine, not just arped for, that the routing could be made to work properly without being asymmetric?
