### ISSUE TITLE
Why is MetalLB supperior to externalIPs?

### ISSUE THREAD

**Issue by spuder** [google/metallb#386]
The documentation says 

>Bare metal cluster operators are left with two lesser tools to bring user traffic into their clusters, “NodePort” and “externalIPs” services. Both of these options have significant downsides for production use, which makes bare metal clusters second class citizens in the Kubernetes ecosystem.

As a new user, I don’t understand why externalIPs are painful, and why MetalLB is better.

**Comment by danderson** [comment]
Roughly two things:

- Using `externalIPs` requires you to manage IP allocation yourself. This works fine on small deployments, but doesn't scale when you want a larger number of ephemeral IPs (similar to what cloud providers offer). MetalLB gives you a way to scalably manage IP allocations out of a large pool. Of course, you can implement that yourself with externalIPs as well.
- When using externalIPs, you have to configure your network to route traffic to your nodes. externalIPs by itself just translates to each node going "if I receive any packets for this IP, I'll send them to these pods". You still have to get the network to send packets to the right place, handle healthchecking so that you don't blackhole traffic, and so forth. MetalLB takes care of that for you, either using BGP or ARP/NDP. Again, you can implement all that with externalIPs (or just statically configure the network and hope nothing ever goes down), but externalIPs by itself does not provide any of that functionality.

With all that said, if externalIPs does what you need, then there's nothing wrong with it! From an implementation perspective, externalIPs implements a subset of what LoadBalancers do, namely it does only the "handle packets when they arrive at the node" part of the equation, without handling allocation or network configuration. If that's all you need, then it's a fine option.
