### ISSUE TITLE
Layer2  failover notify script

### ISSUE THREAD

**Issue by blacs30** [google/metallb#409]
**Is this a bug report or a feature request?**:
Feature request / question

I'm planning on using metallb in my Kubernetes cluster. My provider gives failover IPs but they have to be either manually or via API assigned to a host.

In Keepalived I use the notify script to call an API so that my failover IP is assigned to the new master host.
Is there a way in metallb to achieve similar? If it's currently not possible what other way could solve that problem?

Would it make sense to implement this in metallb?

**Comment by alexlovelltroy** [comment]
I'm not sure I understand what you'd be using the LoadBalancer for in this case.  Since all nodes running metallb can offer the same ip address through the speakers, there shouldn't be  a need for failover ips.

**Comment by blacs30** [comment]
I was reading that documentation https://metallb.universe.tf/concepts/layer2/ and I understand it that way that the service IP would failover to another node in case of failure.

I do only have 1 IP which I would like to use.

Even if metallb can offer the same ip address on each node routing would not work as I have to change the assignment of IP = host on the hosting provider side via API, keepalived has the notify script which can be used for this.

**Comment by danderson** [comment]
I'm unlikely to support this use case. MetalLB is specifically not designed to work in cloud environments where external magic is required to make IPs work.

The cloud provider should write and publish their own LB implementation that does the correct integration with their cloud platform, or _potentially_ send a PR to add that support as a protocol in MetalLB. The latter is still weird, because MetalLB will always be a half-hearted integration with their environment, and they would be better off just creating their own from scratch that does everything (e.g. including automatic IP allocation).
