### ISSUE TITLE
multi-arch docker images

### ISSUE THREAD

**Issue by miekg** [google/metallb#42]
**Is this a bug report or a feature request?**:

feature request

**What happened**:

I need multi arch images. In a k8s environment this means: amd64 arm arm64 ppc64le s390x
It will also mean using `manifest-tool` to upload this to docker hub.

See: https://github.com/coredns/coredns/blob/master/Makefile.release#L139

The above link builds a static go binary using the host machine, i.e. not via a layered docker image. It represents the simplest way we could integrate with coredns.

To be fair: I only need arm images.

I will probably hack around quite a bit; but I'm not sure if it will result in a pull request as it will do it in a Makefile, I also don't understand fabfile.py

**Comment by danderson** [comment]
Potential slight complication is that I'm using quay.io to host the container images, mostly because they supported better build triggering for multi-branch builds.

So (a) figure out if quay supports the correct version of the repository API, (b) we'll probably have to switch from "travis triggers quay.io build" to "travis does all the builds and pushes them". That loses us the nice "automated build" badge, but I don't *think* we have a choice?

I'll hack on this tonight. Since I'm the only one with access to the quay.io repository and the travis stuff, it makes sense for me to take this and iterate.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [google/metallb] multi-arch doc..." ]
>Potential slight complication is that I'm using quay.io to host the container images, mostly because they supported better build triggering for multi-branch builds.
>
>So (a) figure out if quay supports the correct version of the repository API, (b) we'll probably have to switch from "travis triggers quay.io build" to "travis does all the builds and pushes them". That loses us the nice "automated build" badge, but I don't *think* we have a choice?
>
>I'll hack on this tonight. Since I'm the only one with access to the quay.io repository and the travis stuff, it makes sense for me to take this and iterate.

Ok, doing this in travis might be difficult, but would be nice if it works.

Once my Pi cluster is up and running (eow) - I need arm images, but I can build 
and push those do docker hub myself.

**Comment by danderson** [comment]
I think it would be nice to preserve automatic builds for all branches, so we have :latest, :latest-arm, ... That's why I want to try getting this into travis, because it's already aware of the branches, and the deploy stage is effectively a clean docker container with the code checked out... So it should be equivalent to a manual build.

I'll still add a fabric command to build+push manually, so that for development you can push to your own hub account and iterate from there.

**Comment by xnaveira** [comment]
I nice side effect of introducing the **registry** input variable in the ```fab push``` command is that now you can write ie ```fab push:registry=xnaveira``` and it gets pushed to your dockerhub account. One would still need to introduce a parameter in the manifests so set image triggers a pull from the right repo though.

**Comment by danderson** [comment]
- [ ] Create a single Dockerfile per metallb binary, replacing the current templated mess.
- [ ] Add a fabric command to build images for metallb, that allows changing registry, tag, arch. So for example I can tell it to build quay.io/metallb/controller:latest-arm64, and it does the right thing.
- [ ] Add a command that uses manifest-tool to push a "fat image" manifest, so we have true multi-arch images for releases.
- [ ] Edit the minikube dev commands to build for the correct arch, but continue doing the same push magic for minikube.

**Comment by danderson** [comment]
Almost there... Remaining items:

- [ ] Make test-bgp-router buildable on !amd64. Plan for that is to embed GoBGP in the test-bgp-router binary, and skip installation of bird/quagga for !amd64. That way amd64 still tests against many routers, and !amd64 has at least 1 router to test with.
- [ ] Update travis stuff to run `make all-arch-images` as the deploy script. May need to convert to a `sudo: true` environment for this, because we need to run docker and I don't think travis supports docker-in-docker.

Currently, `make push` on amd64 works, but deploying the stock metallb manifests from master is broken, because nothing has built a `speaker` container image on quay.io yet.

**Comment by miekg** [comment]
` make push ARCH=arm REGISTRY=miek `

works, did have to merge some stuff for that though.

**Comment by danderson** [comment]
Going to close this, `make all-arch-images` is capable of building and pushing multi-arch images.

Opening a new issue to re-enable CI/CD in this new world.
