### ISSUE TITLE
setcap needed?

### ISSUE THREAD

**Issue by miekg** [google/metallb#51]
**Is this a bug report or a feature request?**:

bug

**What happened**:

~~~
 ---> a1b40cd21f4b
Step 2/6 : MAINTAINER Miek Gieben <miek@miek.nl> @miekg
 ---> Running in b5b184feaff6
 ---> d18c593354ba
Removing intermediate container b5b184feaff6
Step 3/6 : ADD arp-speaker /arp-speaker
 ---> 2af6e2dd2774
Step 4/6 : RUN setcap 'cap_net_bind_service=+ep' /arp-speaker
 ---> Running in 7691f2b8cac0
standard_init_linux.go:185: exec user process caused "exec format error"
The command '/bin/sh -c setcap 'cap_net_bind_service=+ep' /arp-speaker' returned a non-zero code: 1
Error response from daemon: No such image: arp-speaker:latest
~~~
For this to work we need `setcap` for each arch; or something else

But do we *need* `setcap` at all? Does it make sense in a Dockerfile?

**Comment by danderson** [comment]
It... depends. Linux capabilities are notoriously difficult to work with, and capabilities that you grant can get removed for a bunch of stupid reasons.

In this case, you don't need net_bind_service. That's old cruft that I left on controller and bgp-speaker, but it's not necessary. It just lets you bind TCP/UDP ports <=1024.

However, for ARP I _think_ you will need the `net_raw` capability, which allows you to use a bunch of privileged address families and protocols. You could try running arp-speaker with no setcap at all, and no capabilities defined in the manifest, and see if that works. My guess is it won't work, and you need to do _both_ `setcap net_raw=+ep` and grant the pod the `NET_RAW` capability in the manifest (look at the test-bgp-router manifest for an example of granting pod capabilities). You have to do both, otherwise the capability will be masked out.

As for the question of multi-arch setcap... IIRC setcap actually just writes an extra ELF section in the binary, so running `setcap` on the host OS as part of the build process might Just Work, at least for ARM. More esoteric architectures like s390 might not work, but at least that would unblock your testing.

Longer term... I'll look into what setcap is doing exactly. I've looked at that once before, and I believe it should be trivial to implement the tiny piece we need as a platform-agnostic Go helper. But if you can investigate if you actually need the capabilities, and tell me what arp-speaker actually needs, we can come up with a plan at that point.

**Comment by miekg** [comment]
Note I'm currently using this for my Dockerfiles:
~~~
FROM alpine:latest
MAINTAINER Miek Gieben <miek@miek.nl> @miekg
ADD controller /controller

ENTRYPOINT ["/controller", "--logtostderr"]
~~~
(disregard the MAINTAINER)

**Comment by danderson** [comment]
You have stuff working for now by running as root inside the container. I've opened #53 for myself, to figure out a strategy to re-harden the arp-speaker container later on, but for now I think root-in-container is good enough for you to continue hacking.
