### ISSUE TITLE
log spam (without configmap loaded)

### ISSUE THREAD

**Issue by miekg** [google/metallb#60]
**Is this a bug report or a feature request?**:

bug

**What happened**:

When there is no configmap, arp-speaker (which is basically) bgp-speaker, spam the logs every second:
~~~~
I1215 08:23:05.722742       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:06.809627       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:07.846047       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:08.849858       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:09.845065       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:10.895291       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:11.863993       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:12.941418       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:13.905972       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:14.974906       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:15.959814       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:17.022825       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:18.010477       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:19.059729       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:20.115877       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:21.104206       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:22.176145       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
I1215 08:23:23.138874       1 main.go:107] kube-system/kube-controller-manager: stopping announcements, service deleted
I1215 08:23:24.224595       1 main.go:107] kube-system/kube-scheduler: stopping announcements, service deleted
~~~


**What you expected to happen**:

Nothing is being done, it shouldn't log at all.

**Comment by danderson** [comment]
That's expected. In `deleteBalancer`, you need to be careful to not log anything if the delete is a no-op. See bgp-speaker's implementation, it exits early if you deleteBalancer on a name that doesn't have any configured state.

The reason for this is annoying: the k8s leader election library uses Endpoints objects as the lockfile for the leader election, so anything that does leader election pings an Endpoints object every 2s. We have to watch all Services+Endpoints to get all the state we need for announcing, so we receive that endpoint spam. And we can't filter it out, because we have no way to know that these Endpoints are not part of a Service :(.

So yeah, you have to be careful to only log in `deleteBalancer` if you're actually cleaning up some local state.

**Comment by miekg** [comment]
Thanks. I'll clean this up. For now I'm going to focus on the core
functionality of arp-Speaker because it finally runs in my cluster.

**Comment by danderson** [comment]
Reopening, because I think it might be possible to move the logic for ignoring partial service updates into internal/k8s, so that the behaviors in the controllers is a bit less surprising.

**Comment by danderson** [comment]
Hmm, nope. Tried it out, and there's no way to tell if (svc==nil && eps!=nil) means we can safely ignore this. Given the eventual consistency of the client update streaming model, it's impossible to predict if the transition into that state is always "safe", so we _have_ to tell the controller to delete the balancer, just in case.

One example of this state transition:

1. User creates service `foo`. This creates two objects, `service/foo` and `endpoints/foo`. MetalLB gets `SetBalancer(fooSvc, fooEps)`, and it starts announcing.
2. Controller's client connection to k8s gets cut for some reason. This is fine, the controller still has local state, and in the background continuously tries reconnecting.
3. User deletes the `foo` service. MetalLB doesn't get notified yet, because it's not connected to k8s.
4. User configures something to do leader election, _using the name `foo`_. This creates `endpoints/foo`, but not `service/foo`, because this is not a service.
5. Controller's client successfully reconnects to k8s, and starts reconciling state. It sees that upstream state is `svc/foo` is missing, but `eps/foo` exists.

In this scenario, internal/k8s _must_ call `SetBalancer(nil, nil)` to end up in the correct state. If internal/k8s assumes that (svc==nil && eps!=nil) can be ignored, it will leave dangling announcements in the controller.

So, in this situation, we _have_ to call `SetBalancer(nil, nil)` as a precaution, to tell the controller "JFYI, if you have any state for this service, you need to clear it", because we cannot know if the controller is in sync with the upstream k8s intent.

This is a KI for kubernetes, they made a mistake by using Endpoints objects to implement leader election. I think they're planning to move leader election into either a new custom core type, or into a CustomResourceDefinition. So, someday, maybe we can clean this up... But not for at least several more k8s releases :(
