### ISSUE TITLE
MetalLB unable to connect to quagga 0.99.22.4-4 on centos linux

### ISSUE THREAD

**Issue by gayathri-baskaran** [google/metallb#65]
**Is this a bug report or a feature request?**:
question

**What happened**:
Followed the tutorial from https://metallb.universe.tf/tutorial/ and worked fine. when attempting to run quagga on an external server, bgp not able to establish and receiving below error on bgp speaker. 

E1215 20:50:38.805259       1 bgp.go:48] read OPEN from "10.xx.xx.xx:179": EOF
E1215 20:50:50.805889       1 bgp.go:48] read OPEN from "10.xx.xx.xx:179": read tcp 192.168.144.225:54296->10.xx.xx.xx:179: i/o timeout
E1215 20:50:52.806877       1 bgp.go:48] read OPEN from "10.xx.xx.xx:179": read tcp 192.168.144.225:54334->10.xx.xx.xx:179: read: connection reset by peer

**What you expected to happen**:
BGP to establish

**How to reproduce it (as minimally and precisely as possible)**:
Run quagga outside of k8s and attempt to connect. 

**Anything else we need to know?**:

Metallb config map.. 

kubectl describe configmap config -n metallb-system
Name:           config
Namespace:      metallb-system
Labels:         <none>
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","data":{"config":"peers:\n- peer-address: 10.xx.xx.xx\n  peer-asn: 100\n  my-asn: 200\naddress-pools:\n- name: default\n  cidr:\n  -...

Data

config:

peers:
- peer-address: 10.xx.xx.xx
  peer-asn: 100
  my-asn: 200
address-pools:
- name: default
  cidr:
  - 10.xx.xx.xx/26
  advertisements:
  - aggregation-length: 32

**Environment**:
- MetalLB version: master
- Kubernetes version: 1.8.4
- BGP router type/version: quagga-0.99.22.4-4

- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux node-7 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danderson** [comment]
Thanks for the report! Looking at the timeline of the log messages, the timeout is kind of an outlier, there is a more basic problem with talking to your router. The events are:

T=0: speaker successfully connected to your quagga, but your quagga hangs up during the BGP session negotiation (EOF received while trying to read BGP OPEN).
T+2 (not shown in log messages): speaker retries the connection. Quagga answers, but just sits there and does send its BGP OPEN message.
T+12: connection attempt times out, speaker aborts the connection.
T+14: speaker retries again. Quagga initially accepts the connection, but again hangs up before sending BGP OPEN.

From this, these are some things that might be happening:

- Quagga is missing a peer configuration for the k8s machine, so it rejects the connection once we send our BGP OPEN message, and it confirms that we are not an authorized peer.
- MetalLB is advertising a set of BGP options that Quagga does not like, and it hangs up the connection. In theory, it should send a BGP NOTIFICATION message to tell us what's wrong, but we're not decoding it properly. That's very possible.

Let's try to eliminate some options. Can you share your Quagga configuration? On my OSes it's under /etc/quagga, but YMMV.

If you're able to, another useful thing would be to share a packet capture of the BGP session establishment attempts, so that I can look at what's happening on the network. On the quagga node, run `sudo tcpdump -i any -w metallb.pcap tcp port 179`, and leave it running for ~1 minute while MetalLB is trying to connect. Then share the metallb.pcap with me, so I can take a look at the BGP exchange.

**Comment by danderson** [comment]
Another observation: your version of Quagga is pretty old (0.99.22.4 was released in 2013). Another thing you could try, if possible, is to upgrade to a newer version and see if that helps. If it does, I still want to understand why the older quagga doesn't work with metallb, but that's another option to explore to get more information for now.

**Comment by gayathri-baskaran** [comment]
Thanks for the quick response. 

[quagga-config-log.zip](https://github.com/google/metallb/files/1564162/quagga-config-log.zip)

Attaching the pcap and the config file. FYI,  I am able to establish connection between the two quagga server fine.  Meantime, I will try another server with the latest version to see if that helps.

**Comment by danderson** [comment]
Thanks for the data!

The pcap confirms that the TCP connection is establishing, but quagga hangs up when it receives metallb's BGP OPEN message. Usually, that means it's unhappy with some of the capabilities that metallb advertised.

Metallb advertises 3 capabilities:

- "I will give you IPv4 unicast routes"
- "I will give you IPv6 unicast routes" (this is a no-op currently, it's in preparation for ipv6 support)
- "I support 4-byte ASNs"

Multiprotocol BGP was standardized in 2007, so even a 2013 quagga should be happy with it. Same for 4-byte ASNs, published in 2007, so quagga 0.99 should support it just fine.

My main suspect is the IPv6 unicast capability. It's possible quagga is rejecting it because it treats that session as IPv4 only, and so early-rejects even the possibility of IPv6 routes (or maybe quagga's ipv6 support was incomplete in 0.99? I find that hard to believe).

I'm going to prepare a bgp-speaker docker image that doesn't advertise IPv6 support. When it's ready, can you deploy it on k8s and see if the connection establishes?

Also, could you share your quagga logs? I'm curious if it's logging an exact reason why it's rejecting the BGP session.

I'll have an update with a container image for you in a moment...

**Comment by gayathri-baskaran** [comment]
Quagga log seems to be useless.. 

7/12/15 19:58:57 ZEBRA: client 15 says hello and bids fair to announce only bgp routes
2017/12/15 21:59:31 ZEBRA: Could not lock pid_file /var/run/quagga/zebra.pid, exiting
2017/12/15 21:59:35 ZEBRA: Could not lock pid_file /var/run/quagga/zebra.pid, exiting

Let me know when the docker image is ready, i will try it out.

**Comment by danderson** [comment]
Okay, I have a test image for you, at quay.io/metallb/bgp-speaker:bug-65. You can deploy it to your cluster with this incantation:

`kubectl set image -n metallb-system ds/bgp-speaker bgp-speaker=quay.io/metallb/bgp-speaker:bug-65`

That will update your bgp-speaker to this image. Let me know if the session comes up! If it doesn't, I'll bring up a Centos VM and reproduce locally, to debug what quagga is thinking more precisely.

**Comment by gayathri-baskaran** [comment]
Same error. 
1215 23:32:13.013287       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1215 23:32:13.710453       1 main.go:170] Start config update
I1215 23:32:13.710558       1 main.go:222] Peer "10.96.0.100" configured, starting BGP session
I1215 23:32:13.710654       1 main.go:222] Peer "10.96.0.101" configured, starting BGP session
I1215 23:32:13.710688       1 main.go:222] Peer "10.96.0.102" configured, starting BGP session
I1215 23:32:13.710719       1 main.go:222] Peer "10.133.40.4" configured, starting BGP session
I1215 23:32:13.710796       1 main.go:222] Peer "10.133.40.5" configured, starting BGP session
I1215 23:32:13.710834       1 main.go:237] End config update
I1215 23:32:13.710848       1 k8s.go:300] config changed, reconverging all services
I1215 23:32:13.710987       1 main.go:65] default/nginx: start update
I1215 23:32:13.711038       1 main.go:120] default/nginx: announcable, making 1 advertisements
E1215 23:32:13.712288       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
struct { Version uint8; ASN16 uint16; HoldTime uint16; RouterID uint32; OptsLen uint8 }{Version:0x4, ASN16:0xfc00, HoldTime:0xf0, RouterID:0xa600064, OptsLen:0x16}
struct { Version uint8; ASN16 uint16; HoldTime uint16; RouterID uint32; OptsLen uint8 }{Version:0x4, ASN16:0xfc00, HoldTime:0xb4, RouterID:0xa600065, OptsLen:0x1e}
struct { Version uint8; ASN16 uint16; HoldTime uint16; RouterID uint32; OptsLen uint8 }{Version:0x4, ASN16:0xfc00, HoldTime:0x5a, RouterID:0xa600066, OptsLen:0x10}
I1215 23:32:13.714260       1 bgp.go:54] BGP session to "10.96.0.100:179" established
I1215 23:32:13.714277       1 bgp.go:54] BGP session to "10.96.0.101:179" established
I1215 23:32:13.714729       1 bgp.go:54] BGP session to "10.96.0.102:179" established
E1215 23:32:15.713697       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:17.715097       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:19.717088       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:21.718683       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:23.711877       1 bgp.go:48] read OPEN from "10.133.40.5:179": read tcp 192.168.144.225:38938->10.133.40.5:179: i/o timeout
I1215 23:32:23.711984       1 main.go:132] default/nginx: end update
I1215 23:32:23.712100       1 main.go:65] default/nginx: start update
I1215 23:32:23.712134       1 main.go:120] default/nginx: announcable, making 1 advertisements
I1215 23:32:23.712204       1 main.go:132] default/nginx: end update
E1215 23:32:23.720084       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:25.721169       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:27.722631       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:29.724040       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:31.725500       1 bgp.go:48] read OPEN from "10.133.40.4:179": read tcp 192.168.144.225:60796->10.133.40.4:179: read: connection reset by peer
E1215 23:32:33.727194       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:35.712498       1 bgp.go:48] read OPEN from "10.133.40.5:179": read tcp 192.168.144.225:39002->10.133.40.5:179: i/o timeout
E1215 23:32:35.728427       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF
E1215 23:32:37.729933       1 bgp.go:48] read OPEN from "10.133.40.4:179": EOF


Now I  have two servers with quagg 0.99(10.133.40.4) and 1.2.2(10.133.40.5). Both are not able to establish.

**Comment by danderson** [comment]
Hmm, okay, so that wasn't it.

I'm going to try to reproduce locally. The fact that 1.2.2 also fails (but works in my local test setups) means the difference must be either in our quagga configs, or in the network environment.

Here's a few more ideas, while I try to repro:

1. Try setting the session to passive in your quagga configs, with `neighbor 10.133.40.12 passive`. Quagga can never connect to MetalLB anyway because of the way k8s does networking. I wonder if the errors are happening because quagga is trying to initiate connections...
2. Are there intermediate routers between metallb and quagga, or are they on the same L2 network? From the IPs, it looks like they're on the same subnet... But if there is an intermediate router, try adding `neighbor 10.133.40.12 ebgp-multihop` to the quagga config?
3. Try cranking up quagga's verbosity all the way, to see if it says anything interesting about the failing sessions:

```
! Extra debugging spam, add this at the top-level of the config
debug bgp events
debug bgp filters
debug bgp fsm
debug bgp keepalives
debug bgp updates
```

**Comment by gayathri-baskaran** [comment]
All the servers are on same L2 network.  Adding neighbor 10.133.40.12 passive didnt help. 

Finally seeing some bgp logs. But not understanding well. 


Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 [FSM] Timer (start timer expire).
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 [FSM] BGP_Start (Idle->Connect)
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 [Event] Connect start to 10.133.40.12 fd 16
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 [FSM] Non blocking connect waiting result
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 went from Idle to Connect
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 [Event] Connect failed (Operation now in progress)
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 [FSM] TCP_connection_open_failed (Connect->Active)
Dec 16 01:10:56 node-7 bgpd[50458]: 10.133.40.12 went from Connect to Active
Dec 16 01:10:57 node-7 bgpd[50458]: [Event] BGP connection from host 10.133.40.12
Dec 16 01:10:57 node-7 bgpd[50458]: [Event] Make dummy peer structure until read Open packet
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 [FSM] TCP_connection_open (Active->OpenSent)
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 passive open
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 went from Active to OpenSent
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 rcv message type 1, length (excl. header) 24
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 rcv OPEN, version 4, remote-as (in open) 200, holdtime 90, id 136.225.226.159
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 [Event] Transfer accept BGP peer to real (state Active)
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 sending OPEN, version 4, my as 100, holdtime 180, id 136.225.226.133
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 send message type 1, length (incl. header) 53
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 rcv OPEN w/ OPTION parameter len: 14
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 rcvd OPEN w/ optional parameter type 2 (Capability) len 12
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 OPEN has MultiProtocol Extensions capability (1), length 4
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 OPEN has MP_EXT CAP for afi/safi: 1/1
Dec 16 01:10:57 node-7 bgpd[50458]: message index 65 [4-octet AS number] found in capcode_str at position 4 (max is 8)
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 OPEN has 4-octet AS number capability (65), length 4
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 [Event] Accepting BGP peer delete
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 went from OpenSent to Deleted
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 [FSM] Receive_OPEN_message (OpenSent->OpenConfirm)
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 sending KEEPALIVE
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 send message type 4, length (incl. header) 19
Dec 16 01:10:57 node-7 bgpd[50458]: 10.133.40.12 went from OpenSent to OpenConfirm
Dec 16 01:10:59 node-7 bgpd[50458]: Performing BGP general scanning
Dec 16 01:10:59 node-7 bgpd[50458]: scanning IPv4 Unicast routing tables
Dec 16 01:10:59 node-7 bgpd[50458]: scanning IPv6 Unicast routing tables
Dec 16 01:11:02 node-7 bgpd[50458]: Import timer expired.
Dec 16 01:11:07 node-7 bgpd[50458]: 10.133.40.12 [Event] BGP connection closed fd 16
Dec 16 01:11:07 node-7 bgpd[50458]: 10.133.40.12 [FSM] TCP_connection_closed (OpenConfirm->Idle)
Dec 16 01:11:07 node-7 bgpd[50458]: 10.133.40.12 went from OpenConfirm to Idle

**Comment by danderson** [comment]
Thanks for the log! Looking at that, and at the pcap from earlier, I'm seeing a few strange things.

- In the pcap, it looks like there are sometimes 2 BGP connections from the 10.133.40.12 trying to OPEN at the same time, as if 2 bgp-speaker binaries were running on the node. Does that make any kind of sense to you? Maybe:
  - Is 10.133.40.12 a physical k8s node, or is there some VM/NAT kind of stuff going on?
  - Is the peer specified twice in the MetalLB config?
  - Other possibility if I have some kind of race condition in the config reloading logic that might leave a dangling BGP session. That's a worrying prospect, but I'm making a note to check on it.
- In the quagga log, quagga accepts the OPEN-without-v6, sends its own OPEN message, and sends a KEEPALIVE to notify that it's accepted MetalLB's open. Then it times out in the OpenConfirm state, waiting for MetalLB's KEEPALIVE confirmation.
  - This is very different from what the pcap shows. In the pcap, we see quagga close the connection after MetalLB sends its OPEN. Quagga's OPEN and KEEPALIVE packets never make it onto the wire.

The main mystery I want to figure out right now is why the pcap shows 2 concurrent attempts to establish this session. Does `kubectl get pods -n metallb-system` show only 1 bgp-speaker-* pod? It looks like you're expecting a connection from a single peer on the quagga side, so I'm assuming you have a single k8s node... Is that right?

Still trying to reproduce this on my end, so any information about things that might be unusual about your k8s setup would help.

**Comment by danderson** [comment]
Oh, and apologies, you listed your MetalLB config in the original bug report, so I've already got that.

**Comment by danderson** [comment]
One more request: with the :bug-65 version of metallb, could you get me another pcap from the 0.99 quagga machine, same command as last time? I'm very confused by the fact that quagga _seems_ to be sending OPEN+KEEPALIVE, I want to see if a pcap with the :bug-65 speaker actually sees these on the wire. If we do... Then I have a potentially easy way to reproduce this by replaying the BGP exchange by hand.

**Comment by danderson** [comment]
I've set up a 1.2.2 quagga on Debian, on a machine outside my k8s cluster, configured it to match your configs... And I'm peering and announcing just fine, no complaints from quagga :(.

Next steps for me to get closer to your config: spin up a CentOS 7 VM, install quagga 0.99, and see if this is maybe something specific to quagga on Centos...

**Comment by gayathri-baskaran** [comment]
[metallb_pcap.zip](https://github.com/google/metallb/files/1565040/metallb_pcap.zip)
Pcap from the .bug-65 image.

**Comment by danderson** [comment]
Oh! I think I know what's wrong, I think. It's been staring me in the face all this time.

In the BGP OPEN message, MetalLB is announcing the router ID 136.225.226.159, _not_ 10.133.40.12. I'm pretty sure that's a bug no-no for quagga, it wants the router ID to match the neighbor IP for BGPv4 sessions.

I'm guessing your setup looks like: your k8s nodes have public and private interfaces. You're setting up BGP with internal peers, on the private interface. BUT, the node config in k8s says that the node IP is the public IP... And MetalLB uses the IP in the k8s node config as the router ID. So, It's connecting to a private peer, using the wrong IP as router ID. Quagga sees this as an incoming connection from a router ID that's not in its configuration, and terminates the connection without saying anything (because hey, you're not an authorized peer, why should I tell you anything).

Trying to reproduce this locally, if I'm right it should be trivial for me to get the same pcap you were getting...

**Comment by danderson** [comment]
Damnit, that doesn't seem to be it. Tried this by overriding the router ID manually in metallb, but my quagga 0.99 on centos still accepted the session. Now that I think about it, it makes sense... There's no requirement that router ID == neighbor address, and that equality is not true for most router setups.

Back to the drawing board...

**Comment by danderson** [comment]
Can I see the output of `vtysh -c "show ip bgp neighbors"` please?

I did manage to reproduce the EOF while reading the open message, but in my case this was only happening a few times before quagga accepted the connection, so it's just quagga backing off on error, to avoid tight cpu loops.

In `kubectl logs -n metallb-system -l app=bgp-speaker`, do you see any errors for 10.133.40.4 that are _not_ EOF or "connection reset by peer" ? I suspect the EOFs are just quagga in error backoff, and occasionally (every 2-3 minutes), the _real_ error happens that makes quagga continue to backoff.

**Comment by gayathri-baskaran** [comment]
[output.txt](https://github.com/google/metallb/files/1565875/output.txt)

Attached the "show ip bgp neighbors" output. There is no other error in bgp-speaker other than the io timeout, EOF and "connection reset by peer". Quagga output shows that no BGP packet received from this neighbor.

**Comment by danderson** [comment]
I'm running out of ideas, I'm afraid. The `show ip bgp neighbors` output you provided shows that Quagga is sending BGP notification messages to MetalLB, but they never show up in the pcap. All I can think of is that this means we're capturing the wrong traffic, because if Quagga is sending notifications, we should definitely be seeing those in the pcaps.

I'm also unable to reproduce this on my local system. I've tried quagga 0.99 on centos, 1.2.2 on debian, in a variety of configurations, and every time MetalLB is able to peer with quagga, or quagga sends useful notification messages for debugging. :(

One last thing I can offer: if it's possible, could you give me temporary access to your quagga machine and k8s cluster, so that I can do troubleshooting myself directly? Maybe interactive debugging will reveal something new that I didn't think of before. I would need admin/root access, so I completely understand if you're not okay with that. Depending on your timezone/availability, we could do a screenshare so that you can watch what I'm doing, maybe?

Sorry, I know this is very far from ideal, but I'm basically out of ideas and this is the last thing I can think of :(

**Comment by gayathri-baskaran** [comment]
Unfortunately I cannot share my official environment.  I haven't tried to change the kubernetes deployment server.  I am going to try that.  Otherwise I will try it in personal setup and update

**Comment by gayathri-baskaran** [comment]
I am using calico for Kubernetes networking. Like mentioned in #114, Would that be the reason for this issue as well?

**Comment by gayathri-baskaran** [comment]
After using weavenet, connection established.

**Comment by dlxneamtu** [comment]
Hi, Can you tell me how you configured multihop-ttl on metallb configmap? Thanks

**Comment by stevensingh** [comment]
Hi is it even possible to chnage the BGP TTL value in Metallb ?? im having the problems with eBGP peerings between metallb and my routers and it looks like a ttl problem on the metallb side.

**Comment by danderson** [comment]
The TTL on the MetalLB side is the OS default TTL, which should be >64 hops. MetalLB doesn't set any lower TTL at all. If you're having problems with TTL security, it's likely on the quagga side.

**Comment by stevensingh** [comment]
Thank you for the reply thats really useful as cisco where telling me it could be an issue on Metallb
