### ISSUE TITLE
Use one kubernetes client

### ISSUE THREAD

**Issue by miekg** [google/metallb#79]
**Is this a bug report or a feature request?**:

feature request

**What happened**:

After the speakers got merged in #76 we just use 2 k8s clients, this is quite exspensive; we should just use one. In the words of @danderson:

> TODO future cleanup, we can probably have a single k8s client and a single leader elector for all protocols, and do the fanout in this code.

> Each k8s client maintains its own cache of all the objects, and a separate connection to the k8s apiserver, so currently this code is consuming 2x the ram it needs, and making 2x the number of necessary connection (scaling concern).

> Again, no need to change this right now, I'm just braindumping things we should do later.

**Comment by danderson** [comment]
This is actually really important to do immediately, because it turns out you cannot create >1 k8s client per binary. It does process-unique stuff like listen on the HTTP port, register prometheus metrics... So right now the speaker binary just crash-loops when it's deployed.

Working on merging the clients...

**Comment by danderson** [comment]
Quick and dirty hack implemented. Closing this, opening new issue to clean up the code structure once the rate of change in arp et al. slows down.
