### ISSUE TITLE
NDP speaker implementation

### ISSUE THREAD

**Issue by jpds** [google/metallb#83]
**Is this a bug report or a feature request?**: Feature

**What happened**: I noticed that metallb has gained an ARP speaker, which is great for IPv4, however we'll need a NDP speaker for IPv6 once #7 is implemented.

**Comment by danderson** [comment]
Thanks for the report!

Agreed, IPv6 support implies v6 support for all the protocol stacks. My gut feeling is that it'll happen after v0.3. In 0.3 we're adding all the various protocols with compat for k8s 1.8 (i.e. no v6 support). Once we've done that, adding v6 support before k8s 1.10 graduates that support to beta is the logical next step.

**Comment by miekg** [comment]
Is there a good Go library that implements NPD?
@mdlayher's ARP lib, might be whole implementation in MetalLB a breeze.

Implementation wise it looks we're settling on:
* `<proto>_controller.go` in the speaker/ dir
* `internal/<proto>` for protocol details

I'm happy to review PRs. As an intermediate step we could just announce a fake IPv6 address to see if that parts works. Actually hooking it up to k8s and making that all work, will then be step 2.

**Comment by mdlayher** [comment]
I'd actually love to build out an NDP package and may have a need for it for work, but I can't commit to doing so immediately. Best bet for now is probably another small internal package.

**Comment by mdlayher** [comment]
I'm still pretty new to IPv6 but I also implemented DHCPV6: https://github.com/mdlayher/dhcp6

I wonder if prefix delegation would fit with MetalLB as well. Maybe it'll be necessary!

**Comment by mdlayher** [comment]
Looks like I might be getting into NDP in the next couple of days actually, so feel free to assign to me.

Initial game plan is to start putting together a package either on my account or on DO's with a couple of message types set up.

Once that's done, I can at least try to do the non Kubernetes portions since I don't understand the Kubernetes API very well yet.

**Comment by danderson** [comment]
I'm showing that I suck at github... Can I assign issues to non-committers? The assign autocomplete doesn't show you.

**Comment by mdlayher** [comment]
Unsure! Accepted your invitation now.

**Comment by danderson** [comment]
Okay, that did it, looks like I have to invite people to collaborate before I can assign them issues. A bit cumbersome, but we'll make it work :)

Your plan to start with an NDP package SGTM. For reference you may want to consult `internal/arp` to see what kind of API metallb will eventually want, to gracefully plug into the k8s side of things.

As for the integration to k8s - I think it's fine to defer thinking about that until later, because right now afaik there's no non-hard way of setting up a cluster with v6 support for testing. Best to wait a bit for people to write guides on that :). Also, MetalLB's core absolutely doesn't support IPv6 right now, it has hardcoded prefix lengths and .To4()s all over the place. So we'll need to fix that before you can do e2e hacking of NDP support.

**Comment by mdlayher** [comment]
Sounds good to me, and I had certainly planned on using the ARP components as a reference. In fact, at a glance, it looks like the ARP and NDP speakers might be able to share a fair bit of the controller code. We will see.

**Comment by danderson** [comment]
Yeah, right now the controller code in speaker has a lot of duplication across protocols, even for BGP and ARP. I have an issue in here somewhere to refactor those into a more common base. If I get to that before you get to that point, hopefully it'll be an even simpler API. Otherwise, copy/paste FTW, I guess :)

**Comment by danderson** [comment]
Current status: this is implemented, but not tested. I'm undecided on whether to delay 0.4 until I can set up the e2e test harness, or just release it as "this is especially alpha, please file bugs". I'm leaning towards the latter, because Terraform is proving harder than expected to get working, and I just want to get this code in front of more eyeballs. @mdlayher wdyt?

**Comment by mdlayher** [comment]
SGTM.

**Comment by danderson** [comment]
Marking this fixed, since we believe NDP should be working. If we find out that's not true, we can open more bugs :)
